# Generated by Django 3.1.4 on 2021-09-03 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(db_column='log_id', max_length=20)),
                ('login_passwd', models.CharField(db_column='passwd', max_length=120)),
            ],
            options={
                'db_table': 'tb_super',
            },
        ),
        migrations.CreateModel(
            name='CategoryDetails',
            fields=[
                ('c_id', models.AutoField(db_column='c_id', primary_key=True, serialize=False)),
                ('c_name', models.CharField(db_column='c_name', max_length=30)),
                ('c_desc', models.CharField(db_column='c_desc', max_length=200)),
                ('c_img', models.ImageField(db_column='c_img', upload_to='Category/')),
            ],
            options={
                'db_table': 'tb_category',
            },
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(db_column='c_name', max_length=30)),
                ('cust_address', models.CharField(db_column='c_address', max_length=255)),
                ('cust_phno', models.CharField(db_column='c_phno', max_length=10)),
                ('cust_email', models.CharField(db_column='c_email', max_length=40)),
                ('cust_passwd', models.CharField(db_column='c_passwd', max_length=40)),
                ('cust_img', models.ImageField(db_column='c_img', upload_to='Customer/')),
            ],
            options={
                'db_table': 'tb_customer',
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('m_id', models.AutoField(db_column='m_id', primary_key=True, serialize=False)),
                ('m_name', models.CharField(db_column='m_name', max_length=20)),
            ],
            options={
                'db_table': 'tb_main',
            },
        ),
        migrations.CreateModel(
            name='NurseryProduct',
            fields=[
                ('p_id', models.AutoField(db_column='p_id', primary_key=True, serialize=False)),
                ('p_name', models.CharField(db_column='p_name', max_length=20)),
                ('p_desc', models.CharField(db_column='p_desc', max_length=200)),
                ('p_dimension', models.CharField(db_column='p_dimension', max_length=30)),
                ('p_location', models.CharField(db_column='p_location', max_length=20)),
                ('p_color', models.CharField(db_column='p_color', max_length=10)),
                ('p_sales_package', models.CharField(db_column='p_package', max_length=20)),
                ('p_material', models.CharField(db_column='p_material', default='', max_length=20)),
                ('p_shape', models.CharField(db_column='p_shape', default='', max_length=20)),
                ('p_qty', models.IntegerField(db_column='p_qty', null=True)),
                ('p_type', models.CharField(db_column='p_type', default='', max_length=20)),
                ('p_suitable_for', models.CharField(db_column='p_suitable', max_length=20)),
                ('p_seed', models.CharField(db_column='p_seed', max_length=20)),
                ('p_container', models.CharField(db_column='p_container', max_length=20, null=True)),
                ('p_caring_tips', models.CharField(db_column='p_tips', max_length=200, null=True)),
                ('p_features', models.CharField(db_column='p_features', max_length=100)),
                ('p_price', models.FloatField(db_column='p_price')),
                ('p_offer', models.FloatField(db_column='p_offer', default=0)),
                ('p_rating', models.FloatField(db_column='p_rating', default=0)),
                ('p_exp_days', models.IntegerField(db_column='p_expected_days')),
                ('p_img', models.ImageField(db_column='p_img', upload_to='Products/')),
                ('p_stock', models.IntegerField(db_column='p_stock', default=0)),
                ('p_status', models.CharField(default='available', max_length=20)),
                ('cat_id', models.ForeignKey(db_column='cat_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='nursery_app.categorydetails')),
                ('m_id', models.ForeignKey(db_column='m_id', on_delete=django.db.models.deletion.CASCADE, to='nursery_app.maincategory')),
            ],
            options={
                'db_table': 'tb_nursery_product',
            },
        ),
        migrations.AddField(
            model_name='categorydetails',
            name='m_id',
            field=models.ForeignKey(db_column='m_id', on_delete=django.db.models.deletion.CASCADE, to='nursery_app.maincategory'),
        ),
    ]
