# Generated by Django 3.1.4 on 2021-09-03 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursery_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDetails',
            fields=[
                ('cart_id', models.AutoField(db_column='c_id', primary_key=True, serialize=False)),
                ('qty', models.IntegerField(db_column='qty')),
                ('total', models.FloatField(db_column='total')),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.CASCADE, to='nursery_app.customerdetails')),
                ('nursery_product', models.ForeignKey(blank=True, db_column='n_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='nursery_app.nurseryproduct')),
            ],
            options={
                'db_table': 'tb_cart',
            },
        ),
    ]
